FROM centos:latest
MAINTAINER jack sparrow
RUN yum install -y wget
RUN wget https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-12.noarch.rpm
RUN rpm -ivh epel-release-7-12.noarch.rpm
RUN yum install -y openssl shellinabox
